# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiantian_page', '0001_initial'),
        ('tiantian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detailinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiantian_page.GoodsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now=True)),
                ('Ispay', models.BooleanField(default=False)),
                ('momeys', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiantian.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='order_detailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiantian_order.order_info'),
        ),
    ]
