# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiantian_page', '0001_initial'),
        ('tiantian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiantian_page.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiantian.UserInfo')),
            ],
        ),
    ]
